CREATE TABLE join.ORDERS (
     id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     date varchar(255) NOT NULL,
     customer_id int,
     product_name varchar(255) NOT NULL,
     amount int NOT NULL,
     FOREIGN KEY (customer_id) REFERENCES join.CUSTOMERS(id)
);